[package]
name = "trustify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
trustify-auth = { path = "../common/auth", features = ["actix"] }
trustify-graph = { path = "../graph" }
trustify-common = { path = "../common"}
trustify-infrastructure = { path = "../common/infrastructure" }
trustify-entity = { path = "../entity"}
trustify-ingestors = { path = "../ingestors"}
trustify-module-importer = { path = "../modules/importer" }

actix-web = "4"
anyhow = "1.0.72"
clap = { version = "4", features = ["derive"] }
log = "0.4.19"
once_cell = "1.19.0"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.68", features = [ "raw_value" ] }
futures = "0.3"
thiserror = "1"
utoipa = { version = "4", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "4", features = ["actix-web"] }
csaf = "0.5"
sha2 = "0.10.6"
walker-common = "=0.6.0-alpha.8"

[dev-dependencies]
url-escape = "0.1.1"
