[package]
name = "trustify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
trustify-auth = { path = "../common/auth", features = ["actix", "swagger"] }
trustify-common = { path = "../common"}
trustify-infrastructure = { path = "../common/infrastructure" }
trustify-entity = { path = "../entity"}
trustify-module-graph = { path = "../modules/graph" }
trustify-module-ingestor = { path = "../modules/ingestor" }
trustify-module-importer = { path = "../modules/importer" }
trustify-module-storage = { path = "../modules/storage" }

actix-web = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
csaf = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }
walker-common = { workspace = true }

[dev-dependencies]
url-escape = { workspace = true }
