[package]
name = "trustify-module-signature"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
trustify-auth = { workspace = true }
trustify-common = { workspace = true }
trustify-entity = { workspace = true }
trustify-module-storage = { workspace = true }

actix-web = { workspace = true }
anyhow = { workspace = true }
futures-util = { workspace = true }
json-merge-patch = { workspace = true }
log = { workspace = true }
sea-orm = { workspace = true }
sea-query = { workspace = true }
sequoia-openpgp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["full"] }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras", "uuid", "time"] }
utoipa-actix-web = { workspace = true }
walker-common = { workspace = true }

[dev-dependencies]
actix-http = { workspace = true }
test-context = { workspace = true}
test-log = { workspace = true }
trustify-test-context = { workspace = true }
